en:
  languageCode: en
  languageName: "English"
  weight: 1

zh-hans:
  languageCode: zh-Hans
  languageName: "简体中文"
  weight: 2

# ja:
#   languageCode: ja-JP
#   languageName: "日本語"
#   weight: 3

# fr:
#   languageCode: fr-FR
#   languageName: "Français"
#   weight: 4

# de:
#   languageCode: de-DE
#   languageName: "Deutsch"
#   weight: 5

# es:
#   languageCode: es-ES
#   languageName: "Español"
#   weight: 6

# ru:
#   languageCode: ru-RU
#   languageName: "Русский"
#   weight: 7
